// OBJECT ORIENTED PROGRAMMING(OOP)
// OOP IS NOT A PROGRAMMING LANGUAGE
// OOP IS A WAY TO THINK DIFFERENT...FOR YOUR PROGRAM..
// THE PROBLEM WE FACE IN PROGRAMS..ARE ELIMINATED BY OOP
// OOP IS NOT FULL PROOF..BUG CAN STILL COME..
// BEFORE C++...C EXISTS...BUT THE PERSON JOIN OOP WITH C...TO FORM C++
// C++ WAS FIRST KNOWN AS "C WITH CLASSES"..
// C IS A PROCEDURE OR PROCEDURAL ORIENTED PROGRAMMING (POP)..
// C++ IS A OBJECT ORIENTED PROGRAMMING (OOP)...
// IN OOP WE CREATE CLASSES AND THEN OBJECTS...
// WHEN WE BUILD CLASSES NO MEMORY IS ALLOCATED BY CLASS..OR IT'S VARIABLES..
// OOP TREATS DATA AS A CRITICAL ELEMENT..
// ENCAPSULATION..LIKE MEDICINE IS COATED ADN KNOWN AS CAPSULE..SAME LIKE THAT CODE IS WRAP IN ONE PLACE
// ABSTRACTION..MAKES LAYER...SIMPLIFY THE PROGRAM..ARRANGE THEM..
// POLYMORPHISM...IT TAKES DIFFERENT NUMBER AND PARAMETERS AND GIVE DIFFERENT RESULTS..IT IS SIMILAR TO FUNCTION OVERLOADING
// THEREFORE POLYMORPHISM HAS ABILITY TO TAKE MORE THEN ONE FORMS..
// DYNAMIC BINDING..EXAMPLE..USER ENTERS TIME..AND OUTPUT IS A GREETING..SO GREETING DEPENDS ON TIME...SO THE RESULT WILL GET TO KNOW WHEN PROGRAM WILL RUN..
// MESSAGE PASSING...BY USING OBJECT CALLING THE CLASS..AND GIVE SOME FUNCTION..OR ETC
//              BENEFITS OF OOP
// REUSABILITY..USING OBJECTS AND INHERITANCE
// GIVES SECURITY BY HIDING THE DATA
// MULTIPLE OBJECTS USING CAN BE USED
// SOFTWARE COMPLEXITY CAN EASILY BE MANAGED