#include <iostream> //input and output stream(flow of data between i & o)
using namespace std;
int main()
{
    int num1, num2;
    cout << "ENTER THE VALUE OF num1\n"; //<< is called Insertion Operator...
    cin >> num1;                         //>> is called Extraction Operator...
    cout << "ENTER THE VALUE OF num2\n"; //<< is called Insertion Operator...
    cin >> num2;                         //>> is called Extraction Operator...
    cout << "THE SUM IS " << num1 + num2;
    return 0;
}